### ISSUE TITLE
Pellet consumption showing as KG whereas value is Tonne

### ISSUE THREAD

**Issue by Cameleon99** [sarabanjina/mycomfort#3]
Consumption since bulkfill (SENSOR_BOILER_CONSUMPTION_BULKFILL) and Consumption total (SENSOR_BOILER_CONSUMPTION_BULKFILL) are showing in HA as kgs, but in myComfort they show as Tonnes (1t = 1000kgs).

Is this a setting due to me being in the UK or is it being reported wrong? 

Great reporting otherwise, nicely replacing the custom code I required on my Fibaro HC2 which my HA is replacing. 

HA app (KGS)

![5FCB5068-3781-403B-A787-D1FA77D6B0F0](https://user-images.githubusercontent.com/27414924/165553900-c5ad714a-f572-448f-8592-60c96aafa9c8.jpeg)

myComfort (Tonne)

![507CC806-7BCC-41F2-BDB5-5F119A205875](https://user-images.githubusercontent.com/27414924/165553908-91d393e7-13ed-4e74-b091-d6c014cac852.jpeg)

**Comment by Cameleon99** [comment]
If I'm reading the const.py right then you can only have KG so we need to multiply the values by 1000?

**Comment by sarabanjina** [comment]
Hi,

Nice catch! Windhager is reporting value in tonne and HA is expecting value in kg.

I just commit a patch, can you try it?

Cheers,
Nicolas

**Comment by Cameleon99** [comment]
Perfect, that has done it! 

Shame they dont appear to have tonne as a measure as it would look neater on the dashboard.
